# Site settings
title: Yichen Ma
email: yma447@gatech.edu
description: Academic webpage of Ethan Pickering
baseurl: ""
url: ""
affiliation: ISyE at Georgia Tech

# Location info. (shown in footer)
location: >
  Georgia Institute of Technology <br/>
  Atlanta, GA<br/>

# Contact info. (shown in footer)
contact: >
    Contact Yichen via email: <a href="mailto:yma447@gatech.edu" target="_blank">yma447@gatech.edu</a> <br/>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
#  - name: talks
#  - name: service
  - name: research
# - name: software
# - name: team
  - name: teaching

# Do you want to group your publications by year? {true/false}
group_pub_by_year: true

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
